# Generated by Django 4.1.7 on 2023-02-15 21:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('spotifyId', models.CharField(max_length=128)),
                ('artist', models.CharField(max_length=128)),
                ('featuredartists', models.CharField(blank=True, max_length=256)),
                ('year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999)])),
                ('listnumber', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='ListSong',
        ),
    ]
