# Generated by Django 4.1.7 on 2023-02-16 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_song_delete_listsong'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='listowner',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='api.list'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='list',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
