# Generated by Django 4.1.7 on 2023-02-15 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifytoken',
            name='access_token',
            field=models.CharField(default=123, max_length=150),
            preserve_default=False,
        ),
    ]
