# Generated by Django 4.1.7 on 2023-02-17 22:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('spotifyId', models.CharField(max_length=128)),
                ('artist', models.CharField(max_length=128)),
                ('featuredartists', models.CharField(blank=True, max_length=256)),
                ('year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999)])),
                ('listnumber', models.IntegerField()),
                ('listowner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songster.list')),
            ],
        ),
    ]
