# Generated by Django 4.1.7 on 2023-02-18 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songster', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='featuredartists',
            new_name='featured_artists',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='listnumber',
            new_name='list_number',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='listowner',
            new_name='list_owner',
        ),
        migrations.RemoveField(
            model_name='song',
            name='spotifyId',
        ),
        migrations.AddField(
            model_name='song',
            name='spotify_uri',
            field=models.CharField(default=123, max_length=256),
            preserve_default=False,
        ),
    ]
